Week3. Add basket
KarinaTiurina/online-store-react pull request #2
Opened 2018-11-17 21:26 UTC by KarinaTiurina

2018-11-19 08:00 UTC, index01d requested changes
Если избавится от Snake-case'a в именовании файлов и директорий + соблюдать правило "модуль с компонентом должен называться с большой буквы", то можно заименовать ProductCard.js как index.js и импортировать `from '~/src/ProductCard'`, читаться будет лучше

2018-11-19 08:00 UTC, index01d commented on app.js
> +      const basket = {...this.state.basket};
... в данном случае не спасет, массив item'ов останется тем же самым

2018-11-19 08:00 UTC, index01d commented on app.js
> +      basket.items.push({data, count});
если здесь вывести this.state, то окажется что мы на месте поменяли содержимое this.state еще до вызова setState. Нужно использовать concat или spread-оператор

2018-11-19 08:00 UTC, index01d commented on constants/basket.js
> +const basket = {
выглядит лишней декомпозицией, зачем эта константа?

2018-11-19 08:00 UTC, index01d commented on index.js
> +const getBrowser = () => (
полагаю больше не используется

2018-11-19 08:00 UTC, index01d commented on src/product_card/BuyButton.js
> +  <browserContext.Consumer>
Consumer есть, а Provider'a в иерархии нет, поэтому browser никогда не придет

2018-11-19 19:13 UTC, KarinaTiurina commented on app.js
> +      basket.items.push({data, count});
неожиданно, что basket = {...this.state.basket} не копирует объект. Почему в данном случае он не срабатывает? 
Нашла такой вариант: const basketItems = [...this.state.basketItems, data]; Выводила результат в консоль, значения со state разные

2018-11-19 19:17 UTC, KarinaTiurina commented on constants/basket.js
> +const basket = {
думала кроме items хранить и другую информацию о корзине. На данном этапе согласна что это излишнее, всю информацию можно узнать из массива items. Оставила просто массив basketItems

2018-11-19 19:20 UTC, KarinaTiurina commented on src/product_card/BuyButton.js
> +  <browserContext.Consumer>
неиспользуемые файлы/функции убрала

2018-11-19 19:34 UTC, KarinaTiurina commented
Названия файлов и директорий изменила на CamelCase. Пути прописала как '~/src/...'. Интересное свойство с модулями и index.js в корне каждого модуля. Спасибо, буду использовать.

2018-11-20 15:59 UTC, index01d commented on app.js
> +      basket.items.push({data, count});
он срабатывает, но по сути происходит следующее:

- создается новый объект
- все ключи копируются с this.state.basket
- при копировании ключа items в качестве значения ему присваивается ссылка на объект с массивом (сам массив при этом не копируется)
- старый state в ключе basket.items ссылается на тот же массив
- получается в строчке basket.items.push мы доталкиваем новый элемент в этот самый не пересозданный массив

2018-11-20 16:01 UTC, index01d approved these changes

2018-11-20 16:01 UTC, index01d commented on App.js
> +      const basketItems = [...this.state.basketItems, data];
теперь basketItems выглядит кривоватым избыточным названием. Если хочется проявить немного перфекционизма (вполне уместного), то стоит выделить компонент CartContainer и обернуть все приложение в него. В таком компоненте будет храниться только состояние и методы корзины, поэтому ключ можно будет позволить себе назвать просто items

2018-11-22 19:44 UTC, merged