Week6. Redux. Part 1
KarinaTiurina/online-store-react pull request #5
Opened 2018-12-16 11:51 UTC by KarinaTiurina

2018-12-19 19:38 UTC, index01d requested changes

2018-12-19 19:38 UTC, index01d commented on App.js
> +import store from '~/src/store';
желательно импортировать store только в одном модуле (иные варианты приведут к сложностям), если импортируем его здесь, то и код AppRouter'a должен оказаться здесь же в App.js.

2018-12-19 19:38 UTC, index01d commented on App.js
> +    this.historyCb = (location, action = 'PUSH') => {
historyCb можно выделить в src/helpers/history

2018-12-19 19:38 UTC, index01d commented on App.js
> +    this.historyCb = (location, action = 'PUSH') => {
передавать ему store аргументами

2018-12-19 19:38 UTC, index01d commented on AppRouter.js
> +        <Basket>
выглядит так, что Basket более здесь не нужен, контейнер можно спустить по иерархии ниже (ближе непосредственно к презентационному компоненту корзины)

2018-12-28 19:30 UTC, KarinaTiurina commented on AppRouter.js
> +        <Basket>
Ниже App.js вынести не получится: Basket нужен в компонентах (в Switch). Но там код уже перегружен, стоит ли выносить?

2018-12-29 07:30 UTC, index01d approved these changes

2018-12-29 11:15 UTC, merged