Week8. Forms
KarinaTiurina/online-store-react pull request #7
Opened 2019-01-06 20:31 UTC by KarinaTiurina

2019-01-17 17:16 UTC, index01d requested changes

2019-01-17 17:16 UTC, index01d commented on package.json
> +    "cleave.js": "^1.4.7",
в redux-form для этого предназначен https://redux-form.com/6.7.0/examples/normalizing/

в formik предполагается вручную обрабатывать handleChange; пример готовой реализации https://github.com/alexghenderson/formik-field (не рекомендую брать в проект такие редкоиспользуемые зависимости, которые не факт, что будут поддерживаться; однако их можно использовать как пример для своей реализации)

2019-01-17 17:16 UTC, index01d commented on src/actions/Basket.js
> +    [CLEAR_BASKET]: {
очень хочется заменить на просто:
```
{ type: types.CLEAR_BASKET }
```

вложенность здесь ни к чему

2019-01-17 17:16 UTC, index01d commented on src/components/views/Basket/OrderForm/OrderFormContainer.js
> +  console.log('handleSubmit');
в репозитории не должно оставаться отладочной информации

2019-01-17 17:16 UTC, index01d commented on src/components/views/Basket/OrderForm/OrderFormContainer.js
> +  handleSubmit: (values) => handleSubmit(values),
handleSubmit в числе аргументов (вторым аргументом) получает объект FormikBag(https://jaredpalmer.com/formik/docs/api/withformik#handlesubmit-values-values-formikbag-formikbag-void), среди прочего в этом объекте есть доступ к свойствам (ключ props), включая clearBasket (которого не должно быть в values)

2019-01-17 17:16 UTC, index01d commented on src/components/views/Basket/OrderForm/index.js
> +          orderFormFields.map((field) => (
в целом не так уж и плохо если бы эти поля были здесь же, их отъезд в константы несколько затрудняет навигацию по коду и создает лишнюю абстракцию (о которой надо помнить и знать как она устроена)

2019-01-17 17:16 UTC, index01d commented on src/helpers/basket.js
> +export const prepareBasketToOrder = (basketItems) => {
используется только в одном месте и просится чтобы было реализовано там же, опять же дополнительная абстракция, скрывающая реализацию.

2019-01-17 17:16 UTC, index01d commented on src/helpers/basket.js
> +      price_per_product: item.price
camelCase?

2019-01-17 17:16 UTC, index01d commented on src/helpers/basket.js
> +      product_id: item.id,
camelCase?

2019-01-17 17:16 UTC, index01d commented on src/middlewares/basket.js
> +  if (!action[LOAD_BASKET] && !action[SAVE_BASKET] && !action[CLEAR_BASKET]) return next(action);
выглядит так что лучше бы экшену тогда быть ~~
```
{
  [BASKET]: { type: 'LOAD_BASKET' }
}
```

2019-01-17 17:16 UTC, index01d commented on src/middlewares/basket.js
> +  if (!action[LOAD_BASKET] && !action[SAVE_BASKET] && !action[CLEAR_BASKET]) return next(action);
тогда проверка будет покороче

2019-01-17 17:16 UTC, index01d commented on src/reducers/Basket.js
> +const basketCountAndPrice = (basketItems) => {
мутабельно меняется содержимое action'a

2019-01-19 13:21 UTC, KarinaTiurina commented on package.json
> +    "cleave.js": "^1.4.7",
В целом получается если нужна какая-то сложная форма, плюс в проекте уже есть redux, то лучше делать формы через Redux Form

2019-01-19 13:27 UTC, KarinaTiurina commented on src/reducers/Basket.js
> +const basketCountAndPrice = (basketItems) => {
Вынесла подсчет цены и количества сюда, чтобы избежать дублирования кода + дополнительных пробежек по basketItems везде, где нужна цена или количество.

2019-01-20 07:28 UTC, index01d requested changes

2019-01-20 07:28 UTC, index01d commented on src/reducers/Basket.js
> +    itemsCount += item.count
суть не поменялась, напомню что данные передаются по ссылке, по этому здесь ты напрямую меняешь содержимое переданного action для всех остальных пользователей этой структуры,  что неправильно; тогда нужно клонировать аргумент

2019-01-20 07:28 UTC, index01d commented on src/reducers/Basket.js
> +    basketInfo = basketCountAndPrice(action.basket);
если до и после вызова показать action, то окажется что его содержимое поменялось

2019-01-20 18:13 UTC, index01d approved these changes

2019-01-20 18:18 UTC, merged